import { Leaf, Zap, Award, Globe } from "lucide-react";

export const getImpactMetrics = (formattedStats) => [
  {
    id: "co2-offset",
    icon: Leaf,
    title: "Carbon Offset",
    value: formattedStats?.co2Tons || "0",
    unit: "Tons",
    subtext: "CO2 Emissions Saved",
    badge: "Verified Credits",
    badgeColor: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
    detail: `Equivalent to planting ~${formattedStats?.treesPlanted || "0"} mature trees based on real database trading.`,
    highlightCard: true,
  },
  {
    id: "green-power",
    icon: Zap,
    title: "Green Power Traded",
    value: formattedStats?.powerValue || "0",
    unit: formattedStats?.powerUnit || "kWh",
    subtext: "P2P Solar Energy Delivered",
    badge: "Zero Loss Grid",
    badgeColor: "bg-amber-500/10 text-amber-400 border-amber-500/20",
    detail: `Directly peer-traded over ${formattedStats?.stateName || "DISCOM"} distribution grids with 0 transmission loss.`,
  },
  {
    id: "community-savings",
    icon: Award,
    title: "Community Savings",
    value: formattedStats?.savingsFormatted || "₹0",
    unit: formattedStats?.savingsUnit || "",
    subtext: "Electricity Costs Saved",
    badge: "30% Cheaper Tariff",
    badgeColor: "bg-teal-500/10 text-teal-400 border-teal-500/20",
    detail: "Direct monetary savings retained by energy consumers compared to standard DISCOM retail tariffs.",
  },
  {
    id: "connected-prosumers",
    icon: Globe,
    title: "Connected Prosumers",
    value: formattedStats?.prosumers || "0",
    unit: "Nodes",
    subtext: "Active Rooftop Solar Arrays",
    badge: "100% DISCOM Compliant",
    badgeColor: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20",
    detail: `Registered solar prosumer users currently active in database for ${formattedStats?.stateName || "India"}.`,
  },
];
