import {
  ArrowLeftRight,
  BarChart3,
  LayoutDashboard,
  Leaf,
  ShoppingBag,
  User,
  Users,
  WalletCards,
  Zap,
  Activity,
  Award,
  Bell,
  AlertTriangle,
  Settings,
  FileText,
  LifeBuoy,
  Sun,
  PackageCheck,
  TrendingDown
} from "lucide-react";

export const MENUS = {
  prosumer: [
    { label: "Dashboard", path: "/prosumer", icon: LayoutDashboard, end: true },
    { label: "Smart Meter", path: "/prosumer/meter", icon: Zap },
    { label: "My Solar Panels", path: "/prosumer/panels", icon: Sun },
    { label: "My Listings", path: "/prosumer/listings", icon: Leaf },
    { label: "Marketplace", path: "/marketplace", icon: ShoppingBag },
    { label: "Transactions", path: "/prosumer/transactions", icon: BarChart3 },
    { label: "Wallet",       path: "/prosumer/wallet",      icon: WalletCards },
    { label: "Carbon Credits", path: "/prosumer/carbon", icon: Leaf },
    { label: "Certificates",   path: "/prosumer/certificates", icon: Award },
    { label: "Notifications",  path: "/prosumer/notifications", icon: Bell },
    { label: "Help & Support", path: "/support",              icon: LifeBuoy },
    { label: "Profile",      path: "/profile",              icon: User },
    { label: "Settings",     path: "/prosumer/settings",    icon: Settings },
  ],

  consumer: [
    { label: "Dashboard",          path: "/consumer",               icon: LayoutDashboard, end: true },
    { label: "Marketplace",        path: "/marketplace",            icon: ShoppingBag },
    { label: "My Orders",          path: "/consumer/orders",        icon: PackageCheck },
    { label: "Transactions",       path: "/consumer/transactions",  icon: BarChart3 },
    { label: "Wallet",             path: "/consumer/wallet",        icon: WalletCards },
    { label: "Usage Analytics",     path: "/consumer/analytics",     icon: TrendingDown },
    { label: "Disputes",           path: "/consumer/disputes",      icon: AlertTriangle },
    { label: "Carbon Credits",     path: "/consumer/carbon",        icon: Leaf },
    { label: "Notifications",      path: "/consumer/notifications", icon: Bell },
    { label: "Help & Support",     path: "/support",                icon: LifeBuoy },
    { label: "Profile",            path: "/profile",                icon: User },
    { label: "Settings",           path: "/consumer/settings",      icon: Settings },
  ],

  admin: [
    { label: "Dashboard",       path: "/admin",                icon: LayoutDashboard, end: true },
    { label: "Manage Users",    path: "/admin/users",          icon: Users },
    { label: "Solar Panels",    path: "/admin/panels",         icon: Sun },
    { label: "Manage Listings", path: "/admin/listings",      icon: Leaf },
    { label: "Marketplace",     path: "/marketplace",          icon: ShoppingBag },
    { label: "Transactions",   path: "/admin/transactions",   icon: ArrowLeftRight },
    { label: "Grid Dashboard", path: "/admin/grid",           icon: Activity },
    { label: "Pricing Engine", path: "/admin/pricing",        icon: Zap },
    { label: "Carbon Credits", path: "/admin/carbon",         icon: Leaf },
    { label: "Disputes",       path: "/admin/disputes",       icon: AlertTriangle },
    { label: "Reports",        path: "/admin/reports",        icon: FileText },
    { label: "Notifications",  path: "/admin/notifications",  icon: Bell },
    { label: "Help & Support", path: "/support",              icon: LifeBuoy },
    { label: "Settings",       path: "/admin/settings",       icon: Settings },
  ],
};
